### ISSUE TITLE
Nextra.js warning: the repository is shallow cloned, so the latest modified time will not be presented

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#121]
```
[nextra] The repository is shallow cloned, so the latest modified time will not be presented. See https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches to fetch all the history.
```

**Comment by novusnota** [comment]
Initially I wanted to close this saying, that this only happened due to the fetch depth on clone being too shallow (like, when you or GItHub clones a repo using `--depth 1`). But now I realized that our CI does this, which makes all the pages in the docs be "always fresh", i.e. all pages have "Last updated on X" where X is the day of the latest merge to main, which triggered the CI.

If we resolve this, some parts of the docs would appear more stale than others ("Last modified 1000 years ago") and I don't know if that's a good or bad thing :)
