### ISSUE TITLE
Check if there are more undocumented builtin functions

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#163]
see for example #162

**Comment by novusnota** [comment]
Depends on #75.

**Comment by novusnota** [comment]
Hopefully will be closed by #206, as it covers #75. But it doesn't hurt to double-check :)

Going forward, only the formatting/spellchecking issues may cause the same amount of changes, but I'll make sure to make them as focused as possible and targeting only one issue at a time even if that would mean multiple waves of auto-generated changes across the docs. "One issue = one PR" should become a rule and not a suggestion as of today.

**Comment by novusnota** [comment]
Ok, I think that's it — seems like all the built-in functions out there are covered in the docs.
Could you please double-check https://docs.tact-lang.org, @anton-trunov @Gusarich @byakuren-hijiri

**Comment by Gusarich** [comment]
@novusnota why is `sha256` described in Core library - Math instead of Global static functions?

Same question can probably be applied to `require`, `dump`, `dumpStack` and `emptyMap` but I'm not sure if we even need to list them there in a separate way

**Comment by novusnota** [comment]
@Gusarich

I think it's better to put functions to where they belong semantically rather than trying to be faithful about their actual current origin — users of Tact don't really have to know whether function originates from Tact code, TypeScript code or even some dynamic library written in languages with manual memory management and then wrapped nicely to work with Tact code.

They just need to know that the function exists, is accessible from Tact and works in certain ways, throws certain exceptions and that it may or may not be able to resolve some of its values at compilation time. Other details such as where does the function come from is more interesting to the potential contributors to the Tact compiler.

On that note, it may be worthwhile to mention that in the public docs, although I'd leave those details for some sort of CONTRIBUTING.md or ARCHITECTURE.md files in the Tact compiler repo. Those or similar have to be made at some point anyways :)
