### ISSUE TITLE
Improve readability

### ISSUE THREAD

**Issue by Esorat** [tact-lang/tact-docs#406]
I suggest improving the readability of the text. 

https://docs.tact-lang.org/book/send/

<img width="1055" alt="Screenshot 2024-10-09 at 3 22 41 PM" src="https://github.com/user-attachments/assets/01e81142-59c5-44d4-b535-b262b0cff5ea">

**Comment by novusnota** [comment]
Thank you for the report. This is a known problem for the light theme, because the inline code highlighting (those functions in the note, for example) uses the One Dark theme independent of the theme on the website elsewhere.

As a workaround, I suggest using the dark theme instead (switch in top right corner), since dark theme is the main priority and it looks the best.

P.S.:
Block highlighting in light theme works great, so it's only the _inline_ highlighting inside the asides (note, tip, etc.) that has to be addressed in the future, either by adjusting the highlighting engine or removing the highlighting from those asides altogether.
